
    <tr class="bg bg-dark">
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">#</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">MCA File REF</th>
       <!--<th style="border: 1px solid white;">MCA No</th>-->
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">PRE-ALERT DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">MCA B/REF</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">INVOICE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">LTA Num.</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">T1 Num.</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">COMMODITY</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">SUPPLIER</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">AWB Num.</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">SUPPLIER PO Ref.</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">FOB</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">FRET</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">ASSURANCE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">AUTRE FRAIS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CIF</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">WEIGHT</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">ARRIVAL DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">LICENCE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CRF/IR Num.</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CRF DATE RECEIVED</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DGDA IN</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">REF DECLARATION</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DATE DECLARATION</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">REF LIQUIDATION</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DATE LIQUIDATION</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">REF QUITTANCE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DATE QUITTANCE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DGDA OUT</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DGDA DELAY</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CUSTOM DELIVER DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CLEARING STATUS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">ARRIVAL TO DELIVERY DAYS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">NET DAYS EXCL WEEKENDS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DISPACTH/DELIVER DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">STATUS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">REMARQUE</th>
    </tr>