
    <tr class="">
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">#</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">MCA File REF</th>
       <!--<th style="border: 1px solid white;">MCA No</th>-->
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">MCA B/REF</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">ROAD MANIF</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">PRE-ALERTE DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">T1 Number</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">WEIGHT</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">FOB</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">FRET</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">ASSURANCE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">AUTRES FRAIS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CIF</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">INVOICE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">SUPPLIER</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">PO Ref</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">COMMODITY</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">HORSE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">TRAILER 1</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">TRAILER 2/CONTAINER</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">LICENCE Num.</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Date of Expiration</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Numeration of the arrete</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">K'lesa arrival date</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Crossing Date</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Wiski arrival date</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Departure date Wiski</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">AMICONGO&nbsp;ARRIVAL DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">INSP REPORT RECEIVED DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CLEARED BASED ON IR</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CRF Reference</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CRF Received Date</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Declaration Reference</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DGDA In</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Liquidation Reference</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Date&nbsp;Liquidation</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Quittance Reference</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">Date&nbsp;Quittance</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DGDA Out</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DGDA DELAY</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CUSTOM DELIVER DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">CLEARING STATUS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">ARRIVAL TO DELIVERY DAYS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">NET DAYS EXCL WEEKENDS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">DISPACTH/DELIVER DATE</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">STATUS</th>
      <th style="border: 0.2px solid white; background-color: #696969; color: white;">REMARQUE</th>
    </tr>